//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBackup.WPF.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBackup.WPF.Resources.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete FTP connection.
        /// </summary>
        public static string DeleteFTP {
            get {
                return ResourceManager.GetString("DeleteFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete SQL connection.
        /// </summary>
        public static string DeleteSQL {
            get {
                return ResourceManager.GetString("DeleteSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete website.
        /// </summary>
        public static string DeleteWebsite {
            get {
                return ResourceManager.GetString("DeleteWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit FTP connection.
        /// </summary>
        public static string EditFTP {
            get {
                return ResourceManager.GetString("EditFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SQL connection.
        /// </summary>
        public static string EditSQL {
            get {
                return ResourceManager.GetString("EditSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit website.
        /// </summary>
        public static string EditWebsite {
            get {
                return ResourceManager.GetString("EditWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New FTP connection.
        /// </summary>
        public static string NewFTP {
            get {
                return ResourceManager.GetString("NewFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SQL connection.
        /// </summary>
        public static string NewSQL {
            get {
                return ResourceManager.GetString("NewSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New website.
        /// </summary>
        public static string NewWebsite {
            get {
                return ResourceManager.GetString("NewWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
    }
}
